title: "Pooya Karambakhsh"
subtitle: "Economics, data, and systems thinking for equitable futures"
description: "Economics, data, and systems thinking for equitable futures"
url: "https://pooya-karambakhsh.github.io"        
baseurl: ""      
author:
  name: "Pooya Karambakhsh"
  email: pooya@dianoetic.com.au




markdown: kramdown
kramdown:
  input: GFM

timezone: Australia/Sydney
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


google_analytics: G-VHYW1JQDLQ  # replace with tracking ID