title: "Pooya Karambakhsh"
subtitle: "Economist • Data scientist • Researcher"
description: "Economist • Data scientist • Researcher"
url: ""          # add later if deploying
baseurl: ""      # e.g., /pooya-site if using a subpath

markdown: kramdown
kramdown:
  input: GFM

timezone: Australia/Sydney
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag